{{ cookiecutter.svc_name }}:
  name: {{ cookiecutter.svc_name }}
  environment: prod
  resources:
    requests:
      cpu: "250m"
      memory: 50Mi
    limits:
      cpu: "500m"
      memory: 250Mi
ingress:
  host: {{ cookiecutter.svc_name }}.{{ cookiecutter.github_username  }}.com
  name: {{ cookiecutter.svc_name }}.{{ cookiecutter.github_username  }}.com
