---
kind: Service
apiVersion: v1
metadata:
  name: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
  labels:
    k8s-app: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
    ingress.unity3d.com/haproxy: haproxy
  annotations:
    prometheus.io/name: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
    prometheus.io/port: {{ "{{" }} .Values.service.prometheus_port {{ "}}" }}
    prometheus.io/scr{{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}: 'true'
spec:
  selector:
    app: {{ "{{" }} .Values.{{ cookiecutter.svc_name }}.name {{ "}}" }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP